[log]
destination = "stdout"
level = "debug"


[defaults]
alert.repeat = "yes" # repeat alert on each cycle
alert.groups = "all" # alert all configured groups
alert.users = "all"
alert.grace.seconds = 60 # wait 60 seconds before sending another alert

[check]

[check.cpu]
usage.pct = 1
iowait.pct = 20
loadavg = [2,15]

[check.memory]
usage.gb = 1

[check.filesystem.home]
path = "/home"
usage.pct = 30
